export const CREATIVE_BUCKET = {
  industry: "creative",
  primaryTemplate: "template-the-current",
  fallbackTemplate: "template-2",
  roles: [
    "copywriter",
    "content writer",
    "freelance writer",
    "journalist",
    "blogger",
    "editor",
    "content strategist",
    "brand strategist",
    "content creator",
    "photographer",
    "videographer",
    "filmmaker",
    "video editor",
    "music producer",
    "sound designer",
    "3d artist",
    "concept artist",
    "game designer",
    "vfx artist",
  ],
}
